#!/bin/sh

# Where the magic happens :P
jot -rc 24 48 123 | grep -m18 \\w | rs -g 0 18 | pbcopy;

echo "Password is on your pasteboard"

# Uncomment this to overwrite the pasteboard after 30 seconds
#sleep 30
#perl -0e 'rand($.) < 1 && ($line = $_) while <>;' -e \
#'print $line;' /usr/share/emacs/*/etc/spook.lines | pbcopy
